---
apiVersion: csi.ibm.com/v1
kind: "CSIScaleOperator"
metadata:
  name: "ibm-spectrum-scale-csi"
  namespace: "ibm-spectrum-scale-csi-driver"
  labels:
    app.kubernetes.io/name: ibm-spectrum-scale-csi-operator
    app.kubernetes.io/instance: ibm-spectrum-scale-csi-operator
    app.kubernetes.io/managed-by: ibm-spectrum-scale-csi-operator
    release: ibm-spectrum-scale-csi-operator
status: {}
spec:
  scaleHostpath: "< GPFS FileSystem mount Path on CNSS cluster >"

  clusters:
    - id: "< CNSS cluster id >"
      secrets: "secret1"
      secureSslMode: false
      primary:
        primaryFs: "< Filesystem name on CNSS cluster >"
        remoteCluster: "< Remote ClusterID >"
      restApi:
        - guiHost: "< CNSS cluster GUI IP/Hostname >"

    - id: "< Remote Cluster ID >"
      secrets: "remotesecret"
      secureSslMode: false
      restApi:
      - guiHost: "< Remote cluster Cluster GUI IP/Hostname >"

  attacherNodeSelector:
    - key: "scale"
      value: "true"

  provisionerNodeSelector:
    - key: "scale"
      value: "true"

  pluginNodeSelector:
    - key: "scale"
      value: "true"
